### ISSUE TITLE
Problems getting this to work with the german doctolib site.

### ISSUE THREAD

**Issue by PeterPan123456** [BDelacour/DoctolibChecker#1]
First of all thanks for this great project. I tried useing your program for the german doctolib site. I believe that these two sites are very similar. Unfortuanly I'm not to good with python or programing in general. I have a basic understanding but that isn't enough for getting this to work. Maybe you got the time to quickly look into my problem. 

I use `python3 main.py --sites "https://www.doctolib.de/institut/berlin/ciz-berlin-berlin?pid=practice-158431" --telegram-token "REDACTED" --telegram-chat-id "REDACTED"` to run the program. 

I get the following output:

` 
   2021-05-20 11:07:45,515 - doctolib_checker - INFO - Monitoring : `
` - [1. Arena Berlin](https://www.doctolib.de/institut/berlin/ciz-berlin-berlin?pid=practice-158431) => `
` - [2. Messe Berlin/ Halle 21](https://www.doctolib.de/institut/berlin/ciz-berlin-berlin?pid=practice-158434) => `
` - [6. Erika-Heß-Eisstadion](https://www.doctolib.de/institut/berlin/ciz-berlin-berlin?pid=practice-158437) =>  `
` - [5. Velodrom Berlin](https://www.doctolib.de/institut/berlin/ciz-berlin-berlin?pid=practice-158435) =>  `
` - [3. Flughafen Berlin-Tegel/ Terminal C](https://www.doctolib.de/institut/berlin/ciz-berlin-berlin?pid=practice-158436) =>  `
` - [4.  Flughafen Tempelhof/ Hangar 4](https://www.doctolib.de/institut/berlin/ciz-berlin-berlin?pid=practice-158433) => `

followed by 

`Traceback (most recent call last):
  File "main.py", line 142, in <module>
    main(args)
  File "main.py", line 129, in main
    monitor(sites_info, args.telegram_token, args.telegram_chat_id)
  File "main.py", line 79, in monitor
    lowest_next = min(url_next_call.values())
ValueError: min() arg is an empty sequence`

I edited the main.py to change all the https://doctolib.fr URLs to https://doctolib.de . 
The Telegram bot only outputs this message without any more informations:

`Monitoring :
- 1. Arena Berlin => 
- 2. Messe Berlin/ Halle 21 => 
- 6. Erika-Heß-Eisstadion => 
- 5. Velodrom Berlin => 
- 3. Flughafen Berlin-Tegel/ Terminal C => 
- 4.  Flughafen Tempelhof/ Hangar 4 =>`

Maybe it is only a small fix and you would be willing to sacrifice a bit of your time to look into it. I would be really thankfull! If I'm asking for to much than just tell me that. It's understandable if you dont want to use your time for that. 

Thanks in advance.

**Comment by BDelacour** [comment]
Hello ! I wrote it for the French platform but I'll try to fix it for German one.
I'll tell you when it works :)

**Comment by PeterPan123456** [comment]
Hey, Tank you so much! Really appreciate you taking the time to look into it. If you need some help, e.g something translated in order to understand the german site, just write me. I'm willing to help you.

**Comment by BDelacour** [comment]
I'll need some help about laws.
I wrote this script respecting a recent French law saying "If you are under 50 years old and not a priority person (sick, exposed, ...), you can be vaccinated using Pfizer or Moderna if you find a slot before the next end of day".
The script works this way, it only check for first dose of pfizer or moderna until next end of day.

What is the law about this in Germany (or what would you want to have) ?

**Comment by PeterPan123456** [comment]
Alright, the laws for berlin are changing almost every day. Right now it works the following. If you are in priority group 1/2/3 you get vaccinated with pfilzer/moderna or Astrazeneca in the 6 places listed at the top ( and the URL I wrote in the first message). All you have to do is get an appointment. There is no rule with the end of next day like in france. The age doesn't really matter too. When you get an Invite code (Priority Group 1,2 and 3 got one) you can get an appointment.

**Comment by PeterPan123456** [comment]
All the script has to do is to check for free appointments no matter which of these place, what time/day and then forward these informations to telegram.

**Comment by BDelacour** [comment]
Ok fine ! Much simpler !
I have some things to modify, I will do it tonight (I'm working today).
We keep in touch !

**Comment by BDelacour** [comment]
Well, it wasn't too hard finally. I fixed it during my lunch break (see https://github.com/BDelacour/DoctolibChecker/commit/fb0854524e93395ebd74f2ef88eadb75ea3825b7)
Don't hesitate to tell me if something is not working as expected :)

**Comment by PeterPan123456** [comment]
Thank you so much for helping me out. I just set it up and it looks good. I hope that everything works now.
